remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme

title: VPR
description: The Vidding Photosensitivity Relay is meant to serve as a consistent system for denoting photosenstivy triggers in fan-made videos. This is designed to be a community-based collaboration.

collections:
  risks:
    sort_by: shortcode
    output: true

  writing:
    output: true
    # for some reason sort_by was not working, so I've manually input everything...
    order:
      - norisk.md 
      - intro.md 
      - majorminor.md 
      - examples.md 