remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme

title: Vidding Photosensitivity Relay
description: VPR is meant to serve as a consisent system for denoting photosenstivy triggers in fan-made videos. This is designed to be a commuinty-based collboration.
